[tool.black]
skip-string-normalization = true

[tool.mypy]

[[tool.mypy.overrides]]
module = [
       'scipy.*',
       'astropy.*',
       'gwcs.*',
       'jwst.*',
       'photutils.*',
       'importlib.*'
]
ignore_missing_imports = true
