#+title: RIOJA Custom Pipeline for JWST Data Reduction (PID: 1840)

* Installation
** conda environment
First, it is recommended to create a new Python environment using ~conda~ and to work in the virtual environment.
As the RIOJA custom pipeline requires the ~jwst~ public pipeline, please see the latest informaiton here:
- [[https://github.com/spacetelescope/jwst?tab=readme-ov-file][GitHub - spacetelescope/jwst: Python library for science observations from the James Webb Space Telescope]]
If you are not familliar with creating a ~conda~ environment,
[[https://github.com/spacetelescope/jwst?tab=readme-ov-file#installing-latest-releases][#Installing Latest Releases]] and [[https://github.com/spacetelescope/jwst?tab=readme-ov-file#installing-a-dms-operational-build][#Installing a DMS Operational Build]] may help you create the environment and install the ~jwst~ pipeline.

*** Previous information prior to ~jwst~ 1.16.1
As also described in [[https://github.com/spacetelescope/jwst?tab=readme-ov-file#installing-a-dms-operational-build][#Installing a DMS Operational Build]] for versions prior to 1.16.1,
this is an example to create a virtual environment ~jwstcal~ (shared by Ken).
Please specify a <version> that you want to download (like "1.14.0", prior to 1.16.1).
#+begin_src bash
  # for Mac
  conda create -n jwstcal --file https://ssb.stsci.edu/releases/jwstdp/<version>/conda_python_macos-stable-deps.txt
  # for Linux
  conda create -n jwstcal --file https://ssb.stsci.edu/releases/jwstdp/<version>/conda_python_stable-deps.txt

  conda activate jwstcal

  # for Mac
  pip install -r https://ssb.stsci.edu/releases/jwstdp/<version>/reqs_macos-stable-deps.txt
  # for Linux
  pip install -r https://ssb.stsci.edu/releases/jwstdp/<version>/reqs_stable-deps.txt

  pip install jdaviz
  pip install jupyter
  pip install multiprocess        # methods of multiprocessing used by Alex
#+end_src

If you failed ~pip install -r ....txt~, the following code might help you.
#+begin_src bash
  curl https://ssb.stsci.edu/releases/jwstdp/<version>/reqs_macos-stable-deps.txt > reqs_macos-stable-deps.txt
  # Edit the downloaded file to remove "codecov==2.1.12".
  pip install -r reqs_macos-stable-deps.txt
#+end_src

** pip install
You can install ~jwstgo1840~ using ~pip~:
#+begin_src bash
  pip install git+https://github.com/sugayu/jwstgo1840.git
#+end_src
or
#+begin_src bash
  pip install git+ssh://git@github.com/sugayu/jwstgo1840.git
#+end_src

To update the package, you may need to add the ~--upgrade~ option.
#+begin_src bash
  pip install --upgrade git+https://github.com/sugayu/jwstgo1840.git
#+end_src

* Short description
** Concept of the RIOJA custom pipeline
We have developed the RIOJA custom pipeline
to reduce noises in the 3D data cube and subtract a global background in a statistical manner.

The custom pipeline conducts data reduction with two steps.
The first step makes a tentative 3D cube with minimum reduction processes without background subtraction.
Looking through the tentative 3D cube, users will find bright pixels affected by emission lines, which should be masked.
The users give mask information via the config file and go to the next reduction step.
The second step performs strict sigma clipping for outlier pixels and global background subtraction to produce the final data cube.

** Implementation
In the custom pipeline, we added (currently) two reduction steps during the process of the JWST official pipeline.
One is AfterDetector1Pipeline and the other is AfterSpec2Pipeline.

In AfterDetector1Pipeline, there are three additional reduction processes:

  1.masking outliers (including hot pixels),
  1.subtracting 1/f noises,
  1.sigma clipping.

Present pipeline may not need the sigma clipping, so that it is turned off in the example below.

In AfterSpec2Pipeline, there are additional reduction processes:

  1. clipping pixels with MSA_FAILED_OPEN
  1. masking objects signal pixels
  1. sigma clipping
  1. masking slit edges
  1. subtracting global background.
  1. subtracting slit backgrounds (optional)

** Not implemented (or to do)
The custom pipeline does not include

  1. wcs matching,
  1. local background subtraction

Functions needed for wcs matching has been already written in the code,
but this step needs additional emission-line maps created from NIRCam images.
Therefore, the wcs matching is not automatically processed in the current custom pipeline.

From discussions in team meetings and external meetings, we concluded that the flux calibration is converged in the JWST official pipeline.
Therefore, additional flux calibration steps are not implemented.

* Example
** NIRSpec reduction
Examples are written in the example directory.

An example of NIRSpec calibration is written in [[./example/calib_nirspecifu.py]]
Although another example, [[./example/calib_nirspecifu_v0.4.4.py]], is old, it may be helpful to understand how the pipelines are working.

** Create _cal.fits mask
The RIOJA custom pipeline uses masks for bright objects in ~AfterSpec2Pipeline~ in the second reduction step.
The aperture mask will help additional reductions like strict sigma clipping by masking objects.

The pipeline provides aperture mask classes; currently only ~CylinderAperture3D~ is available.
Using the class, users can give aperture parameters through a config file
or can make apertures directly in the calib main file.
Also users can easily create a new mask class by inheriting the abstract ~Aperture3D~ class.
An example of definitions of ~CylinderAperture3D~ masks is:

#+begin_src yaml
  mask:
    CylinderAperture3D:
      radec:                                # CRDS
        - ['10h00m29.850s', '02d13m02.29s']  # Halpha
        - ['10h00m29.850s', '02d13m02.29s']  # [OIII]5007
        - ['10h00m29.850s', '02d13m02.29s']  # [OIII]4959
        - ['10h00m29.850s', '02d13m02.29s']  # Hbeta
        - ['10h00m29.850s', '02d13m02.29s']  # [OII]
      radii: [0.4, 0.4, 0.4, 0.3]           # arcsec
      waves:
        - [5.1218, 5.1278]      # um
        - [3.9073, 3.9125]
        - [3.8705, 3.8741]
        - [3.7945, 3.7985]
        - [2.9083, 2.9137]
#+end_src

The pixel-by-pixel masking by giving a 3D mask cube is under development.

** WCS in _cal.fits
~wcs_calfits~ provides RA, DEC, and wavelengths for _cal.fits.

#+begin_src python
  from jwst import datamodels
  from jwstgo1840.nirspec.background import wcs_calfits

  fname = 'calib/example/jw01840017001_02101_00001_nrs1_2_cal.fits'
  datamodel = datamodels.open(fname)
  radecw = wcs_calfits(datamodel)
#+end_src

* Release Notes
** version 0.6.0
- Adjust this package to the new WCS logic of cal.fits data:
  [[https://github.com/spacetelescope/jwst/pull/9452][JP-3922: Add a slice map to NRS IFU model and WCS by melanieclarke · Pull Request #9452 · spacetelescope/jwst · GitHub]]
- Make jwst directroy to try to separate dependency on jwst package (yet not perfect).

** version 0.5.0
- Make a new example script with much less codes and relying on a config yaml file.
- Make ~JWSTPipelineRunner~ and ~JWSTPipelineConfig~ for a new style of script.

** version 0.4.0
- Add hot pixel masks for F395M/F290LP.
- Change global background subtraction according to patterns made by the four amplifiers.
- Small fix of jwst parameter (~scale1~ -> ~scalexy~) in the example.

** version 0.3.4
- Fix bugs (Detector1 params in example, output directory, 1/f noise subt. w/o masking outliers)

** version 0.3.3
- Apply object masks when computing global background
- Enable to make a name of the final 3d data cube.
  Please use ~product_name~ keyword in ~CreateAsnFile.dump()~ (see ~example/calib_nirspecifu.py~)
- Minor changes:
  - Raise exceptions when object masks are not well defined as we assumed
  - Turn off warnings for sigma_clip when data includes NaN

** version 0.3.2
- Fix the way to import dqflags by applying current jwst pipeline implementation

** version 0.3.1
- Raise errors when nrs2 is processed for inappropreate filters in AfterDetector1Pipeline
- Fix type of datamodels

** version 0.3.0
- Add objmask step to mask objects for 5 sigma clipping

** version 0.2.0
- Add an option to subtract slit backgrounds after global background subtraction
- Mask MSA_FAILED_OPEN
- Improve slit edge masking by increasing edge widths
- Add function to create object masks for cal.fits
